### ISSUE TITLE
Questions about Comparing Experiments and Datasets

### ISSUE THREAD

**Issue by fyyakaxyy** [athn-nik/sinc#4]
Hello, thank you very much for providing such an excellent project.
I noticed that you made a comparison with TEMOS in paper. I have trained TEMOS before, but it is implemented on the KIT-ML dataset, so I would like to ask:

1. How to train TEMOS on the BABEL dataset？
2. How to train SINC on the KIT-ML dataset？

Looking forward to your reply, thank you！

**Comment by athn-nik** [comment]
Hello thanks for the nice words :)

1. To train TEMOS on BABEL you might want to look at our previous project: https://github.com/athn-nik/teach 
In that project it is possible to train TEMOS on BABEL if you set `data.dtype=seg+seq` when running the training script.
2. This is infeasible since KIT-ML contains single action descriptions and SINC is essentially a pipeline for synthetic spatial compositions. It depends on why you need to train it on KIT-ML. You can use SINC to create synthetic compositions of the AMASS sequences that are in KIT and then use them in your training to augment your data.

**Comment by fyyakaxyy** [comment]
> 你好，谢谢你的好话:)
> 
> 1. 要在 BABEL 上训练 TEMOS，您可能需要查看我们之前的项目： https://github.com/athn-nik/teach 在该项目中，如果您在运行训练脚本时设置了 TEMOS，则可以在 BABEL 上训练 TEMOS。`data.dtype=seg+seq`
> 2. 这是不可行的，因为KIT-ML包含单一动作描述，而SINC本质上是合成空间组合的管道。这取决于你为什么需要在KIT-ML上训练它。您可以使用 SINC 创建 KIT 中 AMASS 序列的合成组合，然后在训练中使用它们来扩充数据。

Thank you for your reply！
